name: "run tests"
description: "run the test suite"

runs:
  using: "composite"
  steps:
    - name: install node
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
      with:
        node-version: "18"

    - name: cache dependencies
      uses: actions/cache@a2ed59d39b352305bdd2f628719a53b2cc4f9613
      with:
        path: |
          node_modules
          package-lock.json
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: install dependencies
      shell: bash -euxo pipefail {0}
      run: npm ci

    - name: set up doctl
      uses: digitalocean/action-doctl@135ac0aa0eed4437d547c6f12c364d3006b42824
      with:
        version: "latest"
        token: ${{env.DIGITALOCEAN_API_TOKEN}}

    - name: registry login
      shell: bash -euxo pipefail {0}
      run: doctl registry login --read-only --expiry-seconds 30

    - name: run development tests
      shell: bash -euxo pipefail {0}
      run: npm run test:ci

    - name: send coverage to codecov
      uses: codecov/codecov-action@0cfda1dd0a4ad9efc75517f399d859cd1ea4ced1
      with:
        token: ${{ env.CODECOV_TOKEN }}
