name: "Run tests"
description: "Run the test suite"

runs:
  using: "composite"
  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: "18"

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          package-lock.json
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      run: npm ci

    - name: Set up doctl
      uses: digitalocean/action-doctl@v2
      with:
        version: "latest"
        token: ${{env.DIGITALOCEAN_API_TOKEN}}

    - name: Registry login
      run: doctl registry login --read-only --expiry-seconds 30

    - name: Run development tests
      run: npm run test:ci

    - name: Send coverage results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ env.CODECOV_TOKEN }}
