name: CI Pipeline

on:
  pull_request:
    branches:
      - development
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  packages: read

env:
  DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
  RATE_LIMIT_WINDOW_MS: ${{ secrets.RATE_LIMIT_WINDOW_MS }}
  RATE_LIMIT_MAX: ${{ secrets.RATE_LIMIT_MAX }}
  PORT: ${{ secrets.PORT }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Restore dependencies from cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            package-lock.json
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Set up doctl
        uses: digitalocean/action-doctl@v2
        with:
          version: "latest"
          token: ${{env.DIGITALOCEAN_API_TOKEN}}

      - name: registry login
        run: doctl registry login --read-only

      - name: Run development tests
        run: npm run test

      - name: Send coverage results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ env.CODECOV_TOKEN }}
